get:
  tags:
    - Product
  summary: Get list of products
  description: Get list of products
  operationId: listProducts
  responses:
    '200':
      description: Success
      content:
          application/json:
            schema:
              $ref: ../../components/schemas/v1/product_list.yaml
    '400':
      description: Bad request
      content: 
        application/json:
          schema: 
            $ref: ..\..\components\schemas\Problem.yaml
    '404':
      description: Not found
      content: 
        application/json:
          schema: 
            $ref: ..\..\components\schemas\Problem.yaml